---
- name: Download MS product repository
  get_url:
       url: https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb
       dest: /tmp/packages-microsoft-prod.deb
- name: Update
  apt: update-cache=yes
  become: true         
- name: Install Python
  apt: name=python-apt state=latest
  become: true
- name: Install MS product repository
  apt: deb=/tmp/packages-microsoft-prod.deb
  become: true
- name: Make sure HTTPS is supported by apt
  apt:
     name: apt-transport-https
     state: present
     update_cache: no
  become: true
- name: Install .NET Core SDK
  apt:
     name: dotnet-sdk-3.1
     state: present
     update_cache: yes
  become: true